### PR TITLE
Make cluster definition configurable

### PR DESCRIPTION
**Pull request by xhernandez**
This PR depends on #8.

### CODE REVIEW

**Comment by anoopcs9** [comment]
@xhernandez I think a manual rebase is required.

**Comment by xhernandez** [comment]
The latest update I've sent uses `ipaddr` filter to manage IP networks and addresses in a more natural way (IMO), but it seems it's not available in the CI. Should we add the required modules to the jenkins job or do the IP manipulation in another way ?

**Comment by anoopcs9** [comment]
> The latest update I've sent uses `ipaddr` filter to manage IP networks and addresses in a more natural way (IMO), but it seems it's not available in the CI. Should we add the required modules to the jenkins job or do the IP manipulation in another way ?

Feel free to update https://github.com/samba-in-kubernetes/samba-centosci/blob/main/jobs/scripts/gluster-integration/gluster-integration.sh by adding `ansible-collection-ansible-utils` to related installation step.

**Comment by xhernandez** [comment]
> Feel free to update https://github.com/samba-in-kubernetes/samba-centosci/blob/main/jobs/scripts/gluster-integration/gluster-integration.sh by adding `ansible-collection-ansible-utils` to related installation step.

Done: https://github.com/samba-in-kubernetes/samba-centosci/pull/21

**Comment by anoopcs9** [comment]
@xhernandez
```
TASK [local.defaults : Generate config.yml in ansible directory] ***************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFilterError: The ipaddr filter requires python's netaddr be installed on the ansible controller
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: The ipaddr filter requires python's netaddr be installed on the ansible controller"}
```

I think we need `python3-netaddr`.

**Comment by xhernandez** [comment]
> @xhernandez
> 
> ```
> TASK [local.defaults : Generate config.yml in ansible directory] ***************
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFilterError: The ipaddr filter requires python's netaddr be installed on the ansible controller
> fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: The ipaddr filter requires python's netaddr be installed on the ansible controller"}
> ```
> 
> I think we need `python3-netaddr`.

I missed that one. I created a new PR: https://github.com/samba-in-kubernetes/samba-centosci/pull/22

**Comment by anoopcs9** [comment]
retest this please

**Comment by anoopcs9** [comment]
https://github.com/samba-in-kubernetes/samba-centosci/pull/23 should fix the final pending issue.

**Review by anoopcs9 — APPROVED** [review]
Generally lgtm. Thanks for making the playbooks highly configurable.

**Review by spuiuk — APPROVED** [review]
ACK

Thanks. The changes look good and makes the ansible playbook more flexible to changes in clusters.

**Pull request merged**
