### PR TITLE
sit.cephfs: Add share configured with `vfs_ceph_new`(non-mgr)

### PR DESCRIPTION
**Pull request by anoopcs9**
depends on #117

### CODE REVIEW

**Comment by spuiuk** [comment]
I think instead of adding a new variable, we should just add to the list of variants.  "vfs_new"?

**Comment by anoopcs9** [comment]
> I think instead of adding a new variable, we should just add to the list of variants. "vfs_new"?

There are multiple aspects to be considered here:

- As of now smb mgr module based configuration is based on `backend=cephfs.mgr.vfs` which indicates the need for ceph native method using the second part of the backend specification. This looked more relatable and meaningful.
- Going forward we may include another configuration using proxy. If go with _vfs_new_ we end up with _vfs_new_proxy_. I think _cephfs.vfs.new_proxy_ will be more sensible. Of course this will end up as _cephfs.mgr.vfs_new_proxy_ for the other case.
- Sooner or later we would have only two: _cephfs_ and _cephfs.mgr_. All other variations are supposed to be clubbed together. Till then it might be easier to put anything extra(new vfs module, proxy requirement) other than the setup method choices separately to avoid any complication in intelligently deriving everything from a single variable.

Let me know if you had something else in your mind.

**Comment by anoopcs9** [comment]
> > I think instead of adding a new variable, we should just add to the list of variants. "vfs_new"?
> 
> There are multiple aspects to be considered here:
> 
>     * As of now smb mgr module based configuration is based on `backend=cephfs.mgr.vfs` which indicates the need for ceph native method using the second part of the backend specification. This looked more relatable and meaningful.
> 
>     * Going forward we may include another configuration using proxy. If go with _vfs_new_ we end up with _vfs_new_proxy_. I think _cephfs.vfs.new_proxy_ will be more sensible. Of course this will end up as _cephfs.mgr.vfs_new_proxy_ for the other case.
> 
>     * Sooner or later we would have only two: _cephfs_ and _cephfs.mgr_. All other variations are supposed to be clubbed together. Till then it might be easier to put anything extra(new vfs module, proxy requirement) other than the setup method choices separately to avoid any complication in intelligently deriving everything from a single variable.

I think I'll reverse the order here to first make the change to group possible shares(starting with cephfs) and then rework this PR to add another share(using _vfs_ceph_new_) on top of it.

**Comment by spuiuk** [comment]
I think the code is far too complex now with a number of if conditions causing it to split into multiple code paths. This change adds another such conditions. I think it would be far easier to go straight to grouping now.

**Review by xhernandez — DISMISSED** [review]

**Review by xhernandez — APPROVED** [review]

**Pull request merged**
